### ISSUE TITLE
Ucarp reference is stale

### ISSUE THREAD

**Issue by StefanSchroeder** [enix/ansible-ucarp#1]
In the README, that is also shown prominently on the project startpage, there is a reference to the UCARP project, given as

https://www.pureftpd.org/project/ucarp

As of 2021-04-16, this link does not exist.
Also ucarp.org is not correct. There seems to be something on https://ucarp.wordpress.com/ but no repo is referenced there.
I wonder what the authoritative source for ucarp is.

**Comment by lcaflc** [comment]
There is no longuer any authoritative source for ucarp as the project is basically stopped. It is no longuer shipped in recent distribution releases. This project is only kept as an archive because we still use it on older systems.
