### ISSUE TITLE
[bug] up keyword for down script

### ISSUE THREAD

**Issue by fch25804** [enix/ansible-ucarp#2]
In file [templates/interface_vip.j2#L10](https://github.com/enix/ansible-ucarp/blob/3cef67d515bde9aac417a72e58ebe503612c56d5/templates/interface_vip.j2#L10), the first word should be `down`, not `up`.

**Comment by lcaflc** [comment]
Fixed in version 1.0.1 . Please not that this role is no longuer actively used as the ucarp project is stopped and no recent distribution ship it now.
Thanks.

**Comment by fch25804** [comment]
Oh, I didn't know that! Thank you. Have you heard about a reliable alternative?

**Comment by lcaflc** [comment]
Keepalived is a great software that does vrrp. however it is more complicated to setup than ucarp.  I don't know any alternative that is as simple to use :/
